######################################################################################################################################################
# Input variables                                                                                                                                    #
######################################################################################################################################################
## Tagging variables
variable "common_tags" {
  description = "The common tags to be applied to all resources in this module."
  type        = map(string)
}

variable "company_name" {
  type = object({
    full  = string,
    short = string
  })
}

variable "location_name" {
  description = "The location where to place all resources in this module."
  type = object({
    full  = string,
    short = string
  })
}

variable "resource_group_name" {
  type        = string
  description = "The name of the resource group."
}

## Resource variables
variable "application_short_name" {
  description = "Short name of application."
  type        = string
}

variable "environment" {
  description = "Application's environment."
  type        = string
}

variable "sqldb_name_count_suffix" {
  description = "Optional value to use as suffix for the database name instead of the default 01."
  type        = string
  default     = "01"
}

variable "app_sql_server" {
  description = "Application SQL Server service."
  type = object({
    id                  = optional(string),
    name                = optional(string),
    resource_group_name = optional(string),
    fqdn                = optional(string)
  })
}

variable "mgt_law_id" {
  type        = string
  description = "The Id of the Log Analytics Workspace resource that will receive logs generated by resources of this module."
}

variable "sql_database" {
  description = "SQL Database resource generals."
  type = object({
    storage_account_type = optional(string),
    sku_name             = optional(string),
    max_size_gb          = optional(string)
  })
}

variable "db_readers_group_members" {
  description = "List of Object IDs of members for the database readers group."
  type        = list(string)
  default     = []
}

variable "db_writers_group_members" {
  description = "List of Object IDs of members for the database writers group."
  type        = list(string)
  default     = []
}

variable "db_management_group_members" {
  description = "List of Object IDs of members for the database management group."
  type        = list(string)
  default     = []
}
