## Tagging variables
variable "common_tags" {
  description = "The common tags to be applied to all resources in this module."
  type        = map(string)
}

variable "company_name" {
  type = object({
    full  = string,
    short = string
  })
}

variable "location_name" {
  description = "The location where to place all resources in this module."
  type = object({
    full  = string,
    short = string
  })
}

variable "owner" {
  description = "The username to set as owner in a tag on created resource (e.g. John.Doe@Spendlab.com)."
  type        = string
  default     = "sl"
}

variable "environment" {
  description = "Resource's environment."
  type        = string
}

## Resource variables

variable "subscription_id" {
  description = "The Id of subscription on which SQL Server is created."
  type        = string
}

variable "resource_group" {
  description = "Resource group where application resource will be created."
  type = object({
    id       = optional(string),
    name     = optional(string),
    location = optional(string)
  })
}

variable "sql_server_name_count_suffix" {
  description = "Optional value to use as suffix for the SQL Server name instead of the default 01."
  type        = string
  default     = "01"
}

variable "server_administrators_group_members" {
  description = "List of Object IDs of members for the server administrators group."
  type        = list(string)
  default     = []
}

variable "blob_private_dns_zone_id" {
  description = "The Id of the private DNS zone for blob services."
  type        = string
}

variable "sql_private_dns_zone_id" {
  description = "The Id of the private DNS zone for SQL services."
  type        = string
}

variable "pe_subnet_id" {
  type        = string
  description = "The Id of the subnet where newly created private endpoint resources should have their IP in."
}

variable "mgt_law_id" {
  type        = string
  description = "The Id of the Log Analytics Workspace resource that will receive logs generated by resources of this module."
}

variable "whitelisted_ip_ranges" {
  type = list(object({
    start_ip = string,
    end_ip   = string
  }))
  description = "(Optional) List of IP ranges to whitelist for the SQL Server's network access."
  default     = []
}
