######################################################################################################################################################
# Input variables                                                                                                                                    #
######################################################################################################################################################
## Tagging variables
variable "common_tags" {
  description = "The common tags to be applied to all resources in this module."
  type        = map(string)
}

variable "company_name" {
  type = object({
    full  = string,
    short = string
  })
}

variable "location_name" {
  description = "The location where to place all resources in this module."
  type = object({
    full  = string,
    short = string
  })
}

## Resource variables
variable "environment" {
  description = "Resource's environment."
  type        = string
}

variable "application_short_name" {
  description = "The location where to place all resources in this module"
  type        = string
}

variable "resource_group" {
  description = "Resource group where application resource will be created."
  type = object({
    id       = optional(string),
    name     = optional(string),
    location = optional(string)
  })
}

variable "storage_name_count_suffix" {
  description = "Optional value to use as suffix for the Storage Account name instead of the default 01."
  type        = string
  default     = "01"
}

variable "private_endpoint_subnet_id" {
  type = string
}

variable "blob_private_dns_zone_id" {
  description = "The Id of the private DNS zone for blob services."
  type        = string
}

variable "mgt_law_id" {
  type        = string
  description = "The Id of the Management Log Analytics Workspace resource in that will receive logs generated by resources of this module."
}
